FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

ARG MONGODB_URI
ARG USER_SERVICE_URL
ARG SMTP_EMAIL
ARG SMTP_PASSWORD

ENV PORT=5004
ENV MONGODB_URI=$MONGODB_URI
ENV USER_SERVICE_URL=$USER_SERVICE_URL
ENV SMTP_EMAIL=$SMTP_EMAIL
ENV SMTP_PASSWORD=$SMTP_PASSWORD

EXPOSE 5004

CMD ["node", "dist/index.js"]