FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

ARG MONGODB_URI
ARG INTERNAL_API_KEY
ARG API_GATEWAY_URL

ENV PORT=3003
ENV MONGODB_URI=$MONGODB_URI
ENV INTERNAL_API_KEY=$INTERNAL_API_KEY
ENV API_GATEWAY_URL=$API_GATEWAY_URL

EXPOSE 3003

CMD ["node", "dist/index.js"]